Repository codeready-toolchain/toolchain-operator, pull requests merged in 2019-12, with the labels that each got.

#18 create Che installation at startup
  cmd/manager/main.go
  deploy/example/toolchain.openshift.dev_v1alpha1_cheinstallation_cr.yaml
  deploy/example/toolchain.openshift.dev_v1alpha1_tektoninstallation_cr.yaml
  make/test.mk
  pkg/controller/cheinstallation/che.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  pkg/controller/tektoninstallation/tekton.go
  pkg/test/toolchain/toolchain.go
  pkg/toolchain/create_resource.go
  pkg/toolchain/create_resource_test.go
  pkg/toolchain/labels.go
  test/e2e/toolchain_test.go
Labels: approved, size/L

#19 refactor tekton installation
  cmd/manager/main.go
  make/go.mk
  make/test.mk
  pkg/controller/tektoninstallation/tekton.go
  pkg/controller/tektoninstallation/tektoninstallation_controller.go
  pkg/controller/tektoninstallation/tektoninstallation_controller_test.go
  pkg/test/toolchain/toolchain.go
  pkg/toolchain/create_resource.go
  pkg/toolchain/create_resource_test.go
  test/e2e/toolchain_test.go
Labels: approved, size/L

#22 chore: update CSV an rename it to codeready-toolchain-operator
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/toolchain.openshift.dev_cheinstallations_crd.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/toolchain.openshift.dev_tektoninstallations_crd.yaml
  deploy/olm-catalog/codeready-toolchain-operator/codeready-toolchain-operator.package.yaml
  deploy/olm-catalog/toolchain-operator/0.0.1/toolchain-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-operator/0.0.1/toolchain_v1alpha1_installation_crd.yaml
  deploy/olm-catalog/toolchain-operator/toolchain-operator.package.yaml
  hack/deploy_csv.yaml
  hack/install_operator.yaml
  make/dev.mk
  make/docker.mk
  make/go.mk
  make/test.mk
Labels: approved, size/XXL

#25 fix: add missing cluster permissions to CSV
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/csv-config.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#26 chore: use CSV for deploying in e2e tests
  make/test.mk
Labels: approved, size/S

#21 refactor namespace status phase check
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  test/e2e/toolchain_test.go
  test/wait/awaitility.go
Labels: approved, size/L

#30 Install CRW Operator instead of Che
  pkg/controller/cheinstallation/che.go
Labels: approved, size/S

#29 chore: update OSP to 0.8.1
  pkg/controller/cheinstallation/che.go
  pkg/controller/tektoninstallation/tekton.go
Labels: approved, size/XS

#20 refactor tests
  pkg/controller/tektoninstallation/tektoninstallation_controller_test.go
  pkg/test/toolchain/che_assertion.go
  pkg/test/toolchain/tekton_assertion.go
  pkg/test/toolchain/toolchain.go
Labels: approved, size/S

#28 chore(CRT-310): support only AllNamespaces install mode
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
  hack/install_operator.yaml
  make/go.mk
  make/test.mk
Labels: approved, size/M

#32 message print column added for cheinstallation
  deploy/crds/toolchain.openshift.dev_cheinstallations_crd.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/toolchain.openshift.dev_cheinstallations_crd.yaml
  hack/deploy_csv.yaml
  pkg/apis/toolchain/v1alpha1/cheinstallation_types.go
Labels: approved, size/S

#33 YAML linting config update and fixes
  .codecov.yaml
  .golangci.yml
  .yamllint
  make/lint.mk
Labels: approved, size/S

#27 add makefile goal to generate API files (CRDs, etc.)
  .codecov.yaml
  deploy/crds/toolchain.openshift.dev_cheinstallations.yaml
  deploy/crds/toolchain.openshift.dev_tektoninstallations.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/toolchain.openshift.dev_cheinstallations.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/toolchain.openshift.dev_tektoninstallations.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  make/generate.mk
  make/go-header.txt
  make/go.mk
  make/test.mk
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  tools.go
Labels: approved, size/L

#31 feat: use ownerReference to let uninstall operators
  cmd/manager/main.go
  deploy/cluster_role.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  make/test.mk
  pkg/installation.go
  pkg/installation_test.go
  pkg/test/client.go
  pkg/test/toolchain/che_assertion.go
  pkg/test/toolchain/tekton_assertion.go
  test/e2e/toolchain_test.go
  test/wait/awaitility.go
Labels: approved, size/XL

#37 chore: add generate-release-manifest target
  make/generate.mk
Labels: approved, size/S

#34 chore: add links, maintainers and warn parts to CSV
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/S

#35 replace 'che' with 'workspaces' in installation resource names
  make/test.mk
  pkg/controller/cheinstallation/che.go
Labels: approved, size/XS

#36 chore: deploy csv for every commit in master via travis-ci
  .travis.yml
  README.adoc
Labels: approved, size/M

#38 fix: skip finding tools in travis
  .travis.yml
  make/find-tools.mk
Labels: approved, size/XS

#39 fix: propagate CSV changes to hack files
  hack/deploy_csv.yaml
Labels: approved, size/XS

#40 fixes in e2e test setup/cleanup
  make/test.mk
Labels: approved, size/S

#17 create checluster resource
  deploy/cluster_role.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  make/test.mk
  pkg/apis/apis.go
  pkg/apis/toolchain/v1alpha1/conditions.go
  pkg/controller/cheinstallation/che.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  pkg/test/olm/che_cluster.go
  test/e2e/toolchain_test.go
  test/wait/awaitility.go
  tools.go
Labels: approved, size/XL

#42 chore: update OSP to 0.8.2
  pkg/controller/tektoninstallation/tekton.go
Labels: approved, size/XS

#45 chore: add che prerequisite about needed real user to operator desc
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#46 release: codeready-toolchain-operator 0.1.1
  manifests/0.1.1/codeready-toolchain-operator.v0.1.1.clusterserviceversion.yaml
  manifests/0.1.1/toolchain.openshift.dev_cheinstallations.yaml
  manifests/0.1.1/toolchain.openshift.dev_tektoninstallations.yaml
  manifests/codeready-toolchain-operator.package.yaml
Labels: approved, size/XL
