Repository codeready-toolchain/toolchain-operator, pull requests merged in 2019-11, with the labels that each got.

#12 run e2e test locally against openshift-4 cluster
  .codecov.yaml
  make/docker.mk
  make/test.mk
Labels: approved, size/S

#11 introduce tekton controller
  .codecov.yaml
  cmd/manager/main.go
  deploy/crds/toolchain.openshift.dev_tektoninstallations_crd.yaml
  deploy/example/toolchain.openshift.dev_v1alpha1_tektoninstallation_cr.yaml
  pkg/apis/toolchain/v1alpha1/conditions.go
  pkg/apis/toolchain/v1alpha1/tektoninstallation_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  pkg/che/che.go
  pkg/controller/add_cheinstallation.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  pkg/controller/controller.go
  pkg/controller/tektoninstallation/tektoninstallation_controller.go
  pkg/controller/tektoninstallation/tektoninstallation_controller_test.go
  pkg/tekton/tekton.go
  pkg/test/toolchain/che.go
  pkg/test/toolchain/tekton.go
  pkg/test/toolchain/toolchain.go
  test/e2e/toolchain_test.go
  test/wait/awaitility.go
Labels: approved, size/XXL

#15 corrected some tags and added printcolumn tags
  deploy/crds/toolchain.openshift.dev_cheinstallations_crd.yaml
  deploy/crds/toolchain.openshift.dev_tektoninstallations_crd.yaml
  pkg/apis/toolchain/v1alpha1/cheinstallation_types.go
  pkg/apis/toolchain/v1alpha1/tektoninstallation_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
Labels: approved, size/M

#14 cheinstallation enhancements
  deploy/example/toolchain.openshift.dev_v1alpha1_cheinstallation_cr.yaml
  make/dev.mk
  make/test.mk
  pkg/che/che.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  test/e2e/toolchain_test.go
  test/wait/awaitility.go
Labels: approved, size/XL

#16 create tekton installation at startup
  .gitignore
  cmd/manager/main.go
  deploy/installation/tekton/toolchain.openshift.dev_v1alpha1_tektoninstallation_cr.yaml
  go.mod
  go.sum
  make/clean.mk
  make/go.mk
  make/test.mk
  pkg/controller/cheinstallation/che.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  pkg/controller/tektoninstallation/tekton.go
  pkg/controller/tektoninstallation/tektoninstallation_controller.go
  pkg/controller/tektoninstallation/tektoninstallation_controller_test.go
  pkg/test/toolchain/tekton.go
  pkg/test/toolchain/toolchain.go
  pkg/toolchain/create_resource.go
  pkg/toolchain/create_resource_test.go
  pkg/toolchain/labels.go
  test/e2e/toolchain_test.go
  tools.go
Labels: approved, size/L
