Repository codeready-toolchain/toolchain-operator, pull requests merged in 2020-02, with the labels that each got.

#50 chore: rename 'che' to 'Che' in descriptions, etc.
  cmd/manager/main.go
  deploy/crds/toolchain.openshift.dev_cheinstallations.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/toolchain.openshift.dev_cheinstallations.yaml
  hack/deploy_csv.yaml
  manifests/0.1.0/toolchain.openshift.dev_cheinstallations.yaml
  manifests/0.1.1/toolchain.openshift.dev_cheinstallations.yaml
  pkg/apis/toolchain/v1alpha1/cheinstallation_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  pkg/controller/cheinstallation/che.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  test/e2e/toolchain_test.go
Labels: approved, size/M

#54 remove unused YAML file and installed tool
  deploy/installation/tekton/toolchain.openshift.dev_v1alpha1_tektoninstallation_cr.yaml
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#55 fix(CRT-454): don't set owner reference
  go.mod
  go.sum
  pkg/installation.go
  pkg/installation_test.go
  test/e2e/toolchain_test.go
Labels: approved, size/L

#56 chore: revert changes in manifests files
  manifests/0.1.0/toolchain.openshift.dev_cheinstallations.yaml
  manifests/0.1.1/toolchain.openshift.dev_cheinstallations.yaml
Labels: approved, size/XS

#57 move/merge test utility funcs in a '/test' and '/test/olm' pkgs
  .gitignore
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  pkg/controller/tektoninstallation/tektoninstallation_controller_test.go
  pkg/installation_test.go
  test/assert/awaitility.go
  test/assert/che_cluster.go
  test/assert/che_installation.go
  test/assert/conditions.go
  test/assert/namespace.go
  test/assert/operator_group.go
  test/assert/subscription.go
  test/assert/tekton_installation.go
  test/client.go
  test/client_test.go
  test/constants.go
  test/e2e/toolchain_test.go
Labels: approved, size/L

#58 chore: change displayed names
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#59 do not cache resources in the assertions
  test/assert/che_cluster.go
  test/assert/che_installation.go
  test/assert/namespace.go
  test/assert/operator_group.go
  test/assert/subscription.go
  test/assert/tekton_installation.go
Labels: approved, size/S

#44 chore: add makefile targets helping with releasing&testing new op versions
  README.adoc
  make/generate.mk
  make/manifests.mk
  make/test.mk
Labels: approved, size/L

#60 release: codeready-toolchain-operator 0.1.2
  manifests/0.1.2/codeready-toolchain-operator.v0.1.2.clusterserviceversion.yaml
  manifests/0.1.2/toolchain.openshift.dev_cheinstallations.yaml
  manifests/0.1.2/toolchain.openshift.dev_tektoninstallations.yaml
  manifests/codeready-toolchain-operator.package.yaml
Labels: approved, size/XL

#61 chore: fix the manifests targets and also their description
  README.adoc
  make/manifests.mk
Labels: approved, size/M

#63 chore: prepare for building in Tekton pipeline
  .travis.yml
  make/manifests.mk
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#62 delete CheCluster when CheInstallation is deleted
  deploy/cluster_role.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  make/test.mk
  pkg/apis/toolchain/v1alpha1/conditions.go
  pkg/controller/cheinstallation/che.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  test/assert/che_cluster.go
  test/assert/che_installation.go
  test/assert/operator_group.go
  test/e2e/toolchain_test.go
Labels: approved, size/XL

#64 chore: update operator-sdk to 0.11.0 to build proper CSV
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#65 fix: use correct key when checking operator-sdk binary
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#52 include CheURL in CheInstallation.Status once install of Che is complete
  deploy/crds/toolchain.openshift.dev_cheinstallations.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/toolchain.openshift.dev_cheinstallations.yaml
  hack/deploy_csv.yaml
  pkg/apis/toolchain/v1alpha1/cheinstallation_types.go
  pkg/apis/toolchain/v1alpha1/zz_generated.openapi.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  test/assert/che_cluster.go
  test/assert/che_installation.go
  test/assert/conditions.go
  test/e2e/toolchain_test.go
Labels: approved, size/L
