Repository codeready-toolchain/toolchain-operator, pull requests merged in 2020-01, with the labels that each got.

#49 chore: update openshift/api and openshift/client-go to release-4.2
  go.mod
  go.sum
Labels: approved, size/S

#48 Refactor Che installation
  pkg/apis/toolchain/v1alpha1/conditions.go
  pkg/controller/cheinstallation/che.go
  pkg/controller/cheinstallation/cheinstallation_controller.go
  pkg/controller/cheinstallation/cheinstallation_controller_test.go
  pkg/controller/tektoninstallation/tekton.go
  pkg/controller/tektoninstallation/tektoninstallation_controller.go
  pkg/controller/tektoninstallation/tektoninstallation_controller_test.go
  pkg/test/toolchain/che_assertion.go
  test/e2e/toolchain_test.go
Labels: approved, size/XXL

#47 chore: move Role permissions to ClusterRole
  deploy/cluster_role.yaml
  deploy/olm-catalog/codeready-toolchain-operator/0.0.1/codeready-toolchain-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  hack/deploy_csv.yaml
  make/dev.mk
  make/test.mk
Labels: approved, size/L
